/** Hand-drawn / doodle infographic icons (Icons8 Doodle style). */
const doodle = (name) => `https://img.icons8.com/doodle/96/${name}.png`;

export const ICON_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'business', label: 'Business' },
  { id: 'commerce', label: 'Commerce' },
  { id: 'communication', label: 'Contact' },
  { id: 'growth', label: 'Growth' },
];

export const DOODLE_ICON_LIBRARY = [
  { id: 'clock', name: 'Clock', category: 'business', src: doodle('clock') },
  { id: 'download', name: 'Download', category: 'business', src: doodle('download') },
  { id: 'conference-call', name: 'Team', category: 'business', src: doodle('conference-call') },
  { id: 'megaphone', name: 'Megaphone', category: 'communication', src: doodle('megaphone') },
  { id: 'checked-shield', name: 'Shield', category: 'business', src: doodle('checked-shield') },
  { id: 'globe', name: 'Globe', category: 'business', src: doodle('globe') },
  { id: 'smartphone', name: 'Phone', category: 'communication', src: doodle('smartphone') },
  { id: 'new-post', name: 'Email', category: 'communication', src: doodle('new-post') },
  { id: 'shopping-cart', name: 'Cart', category: 'commerce', src: doodle('shopping-cart') },
  { id: 'credit-card', name: 'Cards', category: 'commerce', src: doodle('credit-card') },
  { id: 'star', name: 'Star', category: 'growth', src: doodle('star') },
  { id: 'calendar', name: 'Calendar', category: 'business', src: doodle('calendar') },
  { id: 'truck', name: 'Delivery', category: 'commerce', src: doodle('truck') },
  { id: 'combo-chart', name: 'Chart', category: 'growth', src: doodle('combo-chart') },
  { id: 'price-tag', name: 'Price tag', category: 'commerce', src: doodle('price-tag') },
  { id: 'shopping-bag', name: 'Shopping bag', category: 'commerce', src: doodle('shopping-bag') },
  { id: 'settings', name: 'Settings', category: 'business', src: doodle('settings') },
  { id: 'checkmark', name: 'Checkmark', category: 'business', src: doodle('checkmark') },
  { id: 'cardboard-box', name: 'Package', category: 'commerce', src: doodle('cardboard-box') },
  { id: 'user', name: 'User', category: 'business', src: doodle('user') },
  { id: 'share', name: 'Share', category: 'communication', src: doodle('share') },
  { id: 'heart', name: 'Heart', category: 'communication', src: doodle('heart') },
  { id: 'chat', name: 'Chat', category: 'communication', src: doodle('chat') },
  { id: 'forward', name: 'Arrow', category: 'communication', src: doodle('forward') },
  { id: 'trophy', name: 'Trophy', category: 'growth', src: doodle('trophy') },
  { id: 'bell', name: 'Notification', category: 'communication', src: doodle('bell') },
  { id: 'gift', name: 'Gift', category: 'commerce', src: doodle('gift') },
  { id: 'bullseye', name: 'Target', category: 'growth', src: doodle('bullseye') },
  { id: 'phone', name: 'Call', category: 'communication', src: doodle('phone') },
  { id: 'building', name: 'Building', category: 'business', src: doodle('building') },
  { id: 'light-on', name: 'Idea', category: 'business', src: doodle('light-on') },
  { id: 'sent', name: 'Sent', category: 'communication', src: doodle('sent') },
  { id: 'handshake', name: 'Handshake', category: 'growth', src: doodle('handshake') },
  { id: 'rocket', name: 'Rocket', category: 'growth', src: doodle('rocket') },
  { id: 'milestone', name: 'Milestone', category: 'growth', src: doodle('milestone') },
  { id: 'presentation', name: 'Presentation', category: 'business', src: doodle('presentation') },
  { id: 'increase', name: 'Growth', category: 'growth', src: doodle('increase') },
  { id: 'technical-support', name: 'Support', category: 'business', src: doodle('technical-support') },
  { id: 'domain', name: 'Website', category: 'communication', src: doodle('domain') },
  { id: 'money-bag', name: 'Revenue', category: 'commerce', src: doodle('money-bag') },
  { id: 'puzzle', name: 'Solution', category: 'business', src: doodle('puzzle') },
];
