/** Default text box + heading / subheading / body presets for the topbar text menu. */
export const TEXT_STYLE_PRESETS = [
  {
    id: 'heading',
    label: 'Add a heading',
    text: 'Add a heading',
    style: {
      fontSize: 48,
      fontWeight: '800',
      color: '#0f172a',
      textAlign: 'left',
      fontFamily: 'Inter, system-ui, sans-serif',
      lineHeight: 1.15,
    },
  },
  {
    id: 'subheading',
    label: 'Add a subheading',
    text: 'Add a subheading',
    style: {
      fontSize: 28,
      fontWeight: '700',
      color: '#334155',
      textAlign: 'left',
      fontFamily: 'Inter, system-ui, sans-serif',
      lineHeight: 1.25,
    },
  },
  {
    id: 'body',
    label: 'Add a little bit of body text',
    text: 'Add a little bit of body text',
    style: {
      fontSize: 16,
      fontWeight: '500',
      color: '#475569',
      textAlign: 'left',
      fontFamily: 'Inter, system-ui, sans-serif',
      lineHeight: 1.5,
    },
  },
];

/** Font combination cards (preview styles are approximate; full styling applied on add). */
export const FONT_COMBINATIONS = [
  {
    id: 'combo-thank-script',
    preview: 'Thank you!',
    text: 'Thank you!',
    style: {
      fontSize: 26,
      fontWeight: '700',
      fontFamily: '"Segoe Script", "Brush Script MT", cursive',
      color: '#2563eb',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-fire-away',
    preview: 'FIRE away',
    text: 'FIRE away',
    style: {
      fontSize: 22,
      fontWeight: '800',
      fontStyle: 'italic',
      fontFamily: 'Inter, sans-serif',
      color: '#ea580c',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-coffee',
    preview: 'Coffee Break',
    text: 'Coffee Break',
    style: {
      fontSize: 24,
      fontWeight: '800',
      fontFamily: 'Georgia, serif',
      color: '#15803d',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-day-life',
    preview: 'A day in my life',
    text: 'A day in my life',
    style: {
      fontSize: 20,
      fontWeight: '600',
      fontFamily: 'Georgia, serif',
      color: '#7c3aed',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-birthday-brush',
    preview: 'Happy BIRTHDAY',
    text: 'Happy BIRTHDAY',
    style: {
      fontSize: 22,
      fontWeight: '700',
      fontFamily: '"Segoe Script", cursive',
      color: '#f8fafc',
      textAlign: 'center',
      textTransform: 'none',
    },
    textEffect: 'outline',
  },
  {
    id: 'combo-golden-hour',
    preview: 'GOLDEN HOUR',
    text: 'GOLDEN HOUR',
    style: {
      fontSize: 20,
      fontWeight: '600',
      fontFamily: 'Georgia, serif',
      color: '#ca8a04',
      letterSpacing: '0.12em',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
  },
  {
    id: 'combo-thank-shadow',
    preview: 'Thank you!',
    text: 'Thank you!',
    style: {
      fontSize: 24,
      fontWeight: '900',
      fontFamily: 'Inter, sans-serif',
      color: '#fef3c7',
      textAlign: 'center',
    },
    textEffect: 'drop',
  },
  {
    id: 'combo-happy-bday',
    preview: 'Happy birthday!',
    text: 'Happy birthday!',
    style: {
      fontSize: 22,
      fontWeight: '700',
      fontFamily: '"Segoe Script", cursive',
      color: '#dc2626',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-glow',
    preview: 'GLOW',
    text: 'GLOW',
    style: {
      fontSize: 28,
      fontWeight: '800',
      fontFamily: 'Inter, sans-serif',
      color: '#ec4899',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    textEffect: 'neon',
  },
  {
    id: 'combo-thank-bold',
    preview: 'THANK YOU',
    text: 'THANK YOU',
    style: {
      fontSize: 26,
      fontWeight: '900',
      fontFamily: 'Rockwell, Georgia, serif',
      color: '#dc2626',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    textEffect: 'drop',
  },
];
