/** Default text box + heading / subheading / body presets for the topbar text menu. */
export const TEXT_STYLE_PRESETS = [
  {
    id: 'heading',
    label: 'Add a heading',
    text: 'Add a heading',
    style: {
      fontSize: 48,
      fontWeight: '800',
      color: '#0f172a',
      textAlign: 'left',
      fontFamily: 'Inter, system-ui, sans-serif',
      lineHeight: 1.15,
    },
  },
  {
    id: 'subheading',
    label: 'Add a subheading',
    text: 'Add a subheading',
    style: {
      fontSize: 28,
      fontWeight: '700',
      color: '#334155',
      textAlign: 'left',
      fontFamily: 'Inter, system-ui, sans-serif',
      lineHeight: 1.25,
    },
  },
  {
    id: 'body',
    label: 'Add a little bit of body text',
    text: 'Add a little bit of body text',
    style: {
      fontSize: 16,
      fontWeight: '500',
      color: '#475569',
      textAlign: 'left',
      fontFamily: 'Inter, system-ui, sans-serif',
      lineHeight: 1.5,
    },
  },
];

/**
 * Font combination cards — preview approximates canvas; full styling via buildTextDisplayStyle on add.
 * @property {boolean} [multiline] — stack lines in the grid preview
 * @property {number} [previewFontSize] — smaller preview in the sidebar card
 */
export const FONT_COMBINATIONS = [
  {
    id: 'combo-thank-script',
    preview: 'Thank you!',
    text: 'Thank you!',
    style: {
      fontSize: 26,
      fontWeight: '700',
      fontFamily: '"Segoe Script", "Brush Script MT", cursive',
      color: '#2563eb',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-fire-away',
    preview: 'FIRE away',
    text: 'FIRE away',
    style: {
      fontSize: 22,
      fontWeight: '800',
      fontStyle: 'italic',
      fontFamily: 'Inter, sans-serif',
      color: '#ea580c',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-coffee',
    preview: 'Coffee Break',
    text: 'Coffee Break',
    style: {
      fontSize: 24,
      fontWeight: '800',
      fontFamily: 'Georgia, serif',
      color: '#15803d',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-day-life',
    preview: 'A day in my life',
    text: 'A day in my life',
    style: {
      fontSize: 20,
      fontWeight: '600',
      fontFamily: 'Georgia, serif',
      color: '#7c3aed',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-birthday-brush',
    preview: 'Happy BIRTHDAY',
    text: 'Happy BIRTHDAY',
    style: {
      fontSize: 22,
      fontWeight: '700',
      fontFamily: '"Segoe Script", cursive',
      color: '#f8fafc',
      textAlign: 'center',
    },
    textEffect: 'outline',
  },
  {
    id: 'combo-golden-hour',
    preview: 'GOLDEN HOUR',
    text: 'GOLDEN HOUR',
    style: {
      fontSize: 20,
      fontWeight: '600',
      fontFamily: 'Georgia, serif',
      color: '#ca8a04',
      letterSpacing: '0.12em',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
  },
  {
    id: 'combo-thank-shadow',
    preview: 'Thank you!',
    text: 'Thank you!',
    style: {
      fontSize: 24,
      fontWeight: '900',
      fontFamily: 'Inter, sans-serif',
      color: '#fef3c7',
      textAlign: 'center',
    },
    textEffect: 'drop',
  },
  {
    id: 'combo-happy-bday',
    preview: 'Happy birthday!',
    text: 'Happy birthday!',
    style: {
      fontSize: 22,
      fontWeight: '700',
      fontFamily: '"Segoe Script", cursive',
      color: '#dc2626',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-glow',
    preview: 'GLOW',
    text: 'GLOW',
    style: {
      fontSize: 28,
      fontWeight: '800',
      fontFamily: 'Inter, sans-serif',
      color: '#ec4899',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    textEffect: 'neon',
  },
  {
    id: 'combo-thank-bold',
    preview: 'THANK YOU',
    text: 'THANK YOU',
    style: {
      fontSize: 26,
      fontWeight: '900',
      fontFamily: 'Rockwell, Georgia, serif',
      color: '#dc2626',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    textEffect: 'drop',
  },
  /* —— Canva-style catalog (reference grid) —— */
  {
    id: 'combo-stats-metric',
    preview: 'NOV 2019\n1,286\nDOCUMENTS',
    text: '1,286',
    multiline: true,
    previewFontSize: 9,
    style: {
      fontSize: 56,
      fontWeight: '800',
      fontFamily: 'Inter, system-ui, sans-serif',
      color: '#f8fafc',
      textAlign: 'center',
      lineHeight: 1.05,
      letterSpacing: '-0.02em',
      backgroundColor: '#1e293b',
      padding: '16px 20px',
      borderRadius: '8px',
    },
  },
  {
    id: 'combo-dapper',
    preview: 'DAPPER',
    text: 'DAPPER',
    style: {
      fontSize: 28,
      fontWeight: '700',
      fontFamily: '"Playfair Display", Georgia, serif',
      color: '#1c1917',
      textAlign: 'center',
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
    },
  },
  {
    id: 'combo-play-gradient',
    preview: 'PLAY',
    text: 'PLAY',
    style: {
      fontSize: 32,
      fontWeight: '900',
      fontFamily: 'Impact, Haettenschweiler, sans-serif',
      textAlign: 'center',
      letterSpacing: '0.04em',
      textGradient: 'linear-gradient(180deg, #c4b5fd 0%, #6366f1 45%, #312e81 100%)',
      textEffect: 'drop',
    },
  },
  {
    id: 'combo-like-follow',
    preview: 'LIKE & FOLLOW',
    text: 'LIKE & FOLLOW',
    style: {
      fontSize: 18,
      fontWeight: '700',
      fontFamily: '"Playfair Display", Georgia, serif',
      color: '#fef3c7',
      textAlign: 'center',
      letterSpacing: '0.06em',
      backgroundColor: '#292524',
      padding: '10px 14px',
      borderRadius: '4px',
    },
  },
  {
    id: 'combo-wild-sale',
    preview: 'Wild SALE',
    text: 'Wild SALE',
    style: {
      fontSize: 24,
      fontWeight: '800',
      fontFamily: '"Segoe Script", cursive',
      color: '#0f172a',
      textAlign: 'center',
      fillColor: '#ffffff',
    },
    textEffect: 'outline',
  },
  {
    id: 'combo-now-join',
    preview: 'NOW',
    text: 'NOW',
    style: {
      fontSize: 30,
      fontWeight: '900',
      fontFamily: 'Inter, sans-serif',
      color: '#ffffff',
      textAlign: 'center',
      letterSpacing: '0.02em',
      textEffect: 'background',
      effectBackground: 'rgba(124, 58, 237, 0.85)',
      padding: '8px 16px',
      borderRadius: '6px',
    },
  },
  {
    id: 'combo-sweet-neon',
    preview: 'Sweet',
    text: 'Sweet',
    style: {
      fontSize: 28,
      fontWeight: '700',
      fontFamily: '"Segoe Script", "Brush Script MT", cursive',
      color: '#f472b6',
      textAlign: 'center',
    },
    textEffect: 'neon',
  },
  {
    id: 'combo-clicks',
    preview: 'CLICKS',
    text: 'CLICKS',
    style: {
      fontSize: 26,
      fontWeight: '900',
      fontFamily: 'Inter, sans-serif',
      color: '#0d9488',
      textAlign: 'center',
      letterSpacing: '-0.02em',
    },
    textEffect: 'drop',
  },
  {
    id: 'combo-spring-collection',
    preview: 'Spring',
    text: 'Spring COLLECTION',
    style: {
      fontSize: 26,
      fontWeight: '800',
      fontFamily: '"Playfair Display", Georgia, serif',
      color: '#166534',
      textAlign: 'center',
      letterSpacing: '0.02em',
    },
  },
  {
    id: 'combo-hustle',
    preview: 'HUSTLE',
    text: 'HUSTLE',
    style: {
      fontSize: 26,
      fontWeight: '900',
      fontFamily: 'Impact, Haettenschweiler, sans-serif',
      color: '#a3e635',
      textAlign: 'center',
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      fontStyle: 'italic',
    },
    textEffect: 'hollow',
  },
  {
    id: 'combo-great-energy',
    preview: 'ENERGY',
    text: 'Great ENERGY',
    style: {
      fontSize: 24,
      fontWeight: '900',
      fontFamily: 'Impact, Haettenschweiler, sans-serif',
      color: '#0f172a',
      textAlign: 'center',
      fontStyle: 'italic',
      letterSpacing: '0.02em',
    },
    textEffect: 'splice',
  },
  {
    id: 'combo-great-work',
    preview: 'Great work!',
    text: 'Great work!',
    style: {
      fontSize: 22,
      fontWeight: '700',
      fontFamily: '"Segoe Script", "Comic Sans MS", cursive',
      color: '#dc2626',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-join-purple',
    preview: 'JOIN',
    text: 'JOIN',
    style: {
      fontSize: 34,
      fontWeight: '900',
      fontFamily: 'Inter, sans-serif',
      color: 'rgba(124, 58, 237, 0.35)',
      textAlign: 'center',
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
    },
  },
  {
    id: 'combo-sale-banner',
    preview: '50% OFF',
    text: 'UP TO 50% OFF!',
    style: {
      fontSize: 20,
      fontWeight: '800',
      fontFamily: 'Inter, sans-serif',
      color: '#ffffff',
      textAlign: 'center',
      textTransform: 'uppercase',
      backgroundColor: '#dc2626',
      padding: '8px 12px',
      borderRadius: '4px',
      letterSpacing: '0.06em',
    },
  },
  {
    id: 'combo-est-premium',
    preview: 'EST. 2012',
    text: 'EST. 2012',
    style: {
      fontSize: 11,
      fontWeight: '600',
      fontFamily: 'Inter, sans-serif',
      color: '#78716c',
      textAlign: 'center',
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
    },
  },
  {
    id: 'combo-content-that',
    preview: 'Content that',
    text: 'Content that CLICKS',
    style: {
      fontSize: 14,
      fontWeight: '600',
      fontFamily: '"Segoe Script", cursive',
      color: '#64748b',
      textAlign: 'center',
    },
  },
  {
    id: 'combo-lime-outline',
    preview: 'GO',
    text: 'GO',
    style: {
      fontSize: 32,
      fontWeight: '900',
      fontFamily: 'Inter, sans-serif',
      color: '#84cc16',
      textAlign: 'center',
      letterSpacing: '0.1em',
    },
    textEffect: 'outline',
  },
  {
    id: 'combo-rose-glow',
    preview: 'love',
    text: 'love',
    style: {
      fontSize: 26,
      fontWeight: '700',
      fontFamily: '"Segoe Script", cursive',
      color: '#fb7185',
      textAlign: 'center',
    },
    textEffect: 'glow',
  },
  {
    id: 'combo-midnight-neon',
    preview: 'NIGHT',
    text: 'NIGHT',
    style: {
      fontSize: 24,
      fontWeight: '800',
      fontFamily: 'Inter, sans-serif',
      color: '#22d3ee',
      textAlign: 'center',
      textTransform: 'uppercase',
      letterSpacing: '0.15em',
    },
    textEffect: 'neon',
  },
  {
    id: 'combo-gold-serif',
    preview: 'LUXE',
    text: 'LUXE',
    style: {
      fontSize: 26,
      fontWeight: '700',
      fontFamily: '"Playfair Display", Georgia, serif',
      color: '#ca8a04',
      textAlign: 'center',
      letterSpacing: '0.25em',
      textTransform: 'uppercase',
    },
  },
  {
    id: 'combo-glitch-pop',
    preview: 'POP',
    text: 'POP',
    style: {
      fontSize: 28,
      fontWeight: '900',
      fontFamily: 'Inter, sans-serif',
      color: '#e879f9',
      textAlign: 'center',
    },
    textEffect: 'glitch',
  },
];
